apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-spring-boot-app-openshift
  title: sample-spring-boot-app-openshift
  annotations:
    janus-idp.io/tekton: sample-spring-boot-app-openshift
    tektonci/build-namespace: demo
    github.com/project-slug: shailendra14k/sample-spring-boot-app-openshift
    sonarqube.org/project-key: shailendra14k_sample-spring-boot-app-openshift
    backstage.io/kubernetes-id: sample-spring-boot-app-openshift
    argocd/app-name: sample-spring-boot-app-openshift
    prometheus.io/rule: container_memory_usage_bytes{pod=~"sample-spring-boot-app-openshift-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"sample-spring-boot-app-openshift-.*"}[5m])|pod
  tags:
    - spring-boot
    - java
    - maven
    - tekton
    - argocd
    - renovate
    - sonarqube
spec:
  type: service
  owner: piomin
  lifecycle: experimental